apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-admission-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 20443
    protocol: TCP
    name: admission-webhook
  type: ClusterIP
  selector:
    app: neuvector-controller-pod